### ISSUE TITLE
Implement the retry logic from the spec

### ISSUE THREAD

**Issue by jkwatson** [newrelic/newrelic-telemetry-sdk-java#108]
See here for details:  https://github.com/newrelic/newrelic-telemetry-sdk-specs/blob/master/communication.md#graceful-degradation

**Comment by breedx-nr** [comment]
Resolved by #124...though there was talk about making the strategy pluggable some day.

**Comment by jkwatson** [comment]
Yep. you created another issue for that. :). #126
