### ISSUE TITLE
Make examples jar runnable with a main method

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-telemetry-sdk-java#116]
Some users might expect the examples jar to be runnable (eg. it has a main class defined in the manifest).  The use case is that a new user clones the repo, looks at some docs, reads some code, and then wants to try it out.  They build the jar with gradle and then try to run it via `java -jar <jar> <insights_key>`.

Right now this doesn't work.  We should make that better, and include docs.

**Comment by breedx-nr** [comment]
Actually, it's been pointed out that we'd need to build a fat jar for this to work...so instead we should  perhaps leverage the gradle application plugin and just do `gradle run`.

**Comment by tbradellis** [comment]
Working on updating the docs for this now.  These can be ran via gradle tasks.
./gradlew telemetry_examples:BoundaryExample -PapiKey=<key>

However, there is a namespace issue in the build.gradle.kts. Opening a PR to address that.

**Comment by tbradellis** [comment]
I submitted this PR: https://github.com/newrelic/newrelic-telemetry-sdk-java/pull/190

**Comment by XiXiaPdx** [comment]
@breedx-nr   i believe this issue is resolved with Brad's PR using gradle. Can I close it?

**Comment by breedx-nr** [comment]
Yup, looks good.  Thanks all!
