### ISSUE TITLE
Information does not appear on API despite using URIoverride and api key.

### ISSUE THREAD

**Issue by litscher** [newrelic/newrelic-telemetry-sdk-java#129]
We have managed to create Opentelemetry Spans without much issue and through debugging, it looks like the spans are using New Relic format. 
We have tested the API key and the URI successfully with the curl command: https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/trace-api/report-new-relic-format-traces-trace-api
We are not receiving any errors whether or not we use the URIoverride. We have forced errors by using the wrong keys. Is there a way to troubleshoot this?

**Comment by jkwatson** [comment]
Hello @litscher .  I'm confused about what issue you're seeing (or not seeing). Can you explain in detail what steps you're taking, what you're expecting to see, and what's not working?

**Comment by litscher** [comment]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/17788855/76354424-cd07da00-62e8-11ea-84f8-ecb078084323.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/17788855/76352828-130f6e80-62e6-11ea-967d-71f88ff4188c.png">
We set up the exporter and BatchSpanProcessor as seen here: https://github.com/newrelic/opentelemetry-exporter-java
However, we overrode the URI with our own. 

We have used this code with Jaeger before but I have redone it with Opentelemetry Spans instead of OpenTracing spans. 

We have modeled the span we created off of the New Relic format for spans that are specified in the above link. We have the service name as well as multiple spans with trace IDs and start and end times (as well as custom attributes). 

When the batch gets sent, though, we are not seeing any data anywhere in the Distributed Tracing interface despite having the correct API key. We are also not getting any errors. 

If we purposely send the data with the wrong API key, there are errors thrown.
```
019 [pool-1-thread-1] WARN com.newrelic.telemetry.transport.BatchDataSender  - Response from New Relic ingest API. Discarding batch recommended.: code: 403, body: {}
1020 [pool-1-thread-1] ERROR com.newrelic.telemetry.TelemetryClient  - Received a fatal exception from the New Relic API. Aborting metric batch send.
com.newrelic.telemetry.exceptions.DiscardBatchException: The New Relic API failed to process this request and it should not be retried.
	at com.newrelic.telemetry.transport.BatchDataSender.sendPayload(BatchDataSender.java:132)
	at com.newrelic.telemetry.transport.BatchDataSender.send(BatchDataSender.java:81)
	at com.newrelic.telemetry.spans.SpanBatchSender.sendBatch(SpanBatchSender.java:52)
	at com.newrelic.telemetry.TelemetryClient.lambda$sendBatch$1(TelemetryClient.java:71)
	at com.newrelic.telemetry.TelemetryClient.sendWithErrorHandling(TelemetryClient.java:89)
	at com.newrelic.telemetry.TelemetryClient.lambda$scheduleBatchSend$2(TelemetryClient.java:80)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
 If we maintain the URI and do not override it, there are no errors thrown. 

So far I  have been able to find only one log message from NewRelic. It was an expected message: 
```
[10 Mar 2020 14:53:07.619] [com.newrelic.telemetry.transport.BatchDataSender:60] main: INFO  - BatchDataSender configured with endpoint https://*****************.newrelic.com/trace/v1
```
As far as I can tell, our spans are formatted correctly. I am trying to figure out what else might be the problem. I have looked through the New-Relic site, this repo and the opentelemetry repo. And I am not sure what I am missing.

**Comment by jkwatson** [comment]
Have you tried enabling audit logging? That can be a useful way to at least see that the data is being sent in the format that you expect.

Also, if there's a problem with sending the data to NR, you can query the `NrIntegrationError` events in Insights or NR-One and you might get something that shows if something is wrong with the data that's being sent in.

What URI are you pointing at, if you're not using the default URI that we provide?

**Comment by litscher** [comment]
When I have enabled audit logging enabled, and use the default URI, these are the only messages received. 

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/17788855/76415067-ebb0b400-636e-11ea-802e-13c56d8665f5.png">

I will try to figure out what the other URI references.

**Comment by jkwatson** [comment]
Make sure you have your logging implementation set to have `com.newrelic.telemetry` logging at DEBUG level; this is the log level the audit logging is set to.

**Comment by litscher** [comment]
Thank you! It looks like we are sending successfully to either URI -- we get a 202 and a requestID Perhaps I am searching for the data incorrectly? I have been using the Distributed Tracing interface.

**Comment by jkwatson** [comment]
Are you setting the service name? If you don't, it'll be hard to find your Spans outside of a direct query. 
Here's an example of doing that:  https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/master/telemetry_examples/src/main/java/com/newrelic/telemetry/examples/TelemetryClientExample.java#L97

**Comment by litscher** [comment]
We appear to be using the wrong Span. We were using the Opentelemetry one.

**Comment by jkwatson** [comment]
I'm confused. How do you send OpenTelemetry spans with our SDK without using our OpenTelemetry exporter?  https://github.com/newrelic/opentelemetry-exporter-java

**Comment by litscher** [comment]
I was using the opentelemetry exporter, but it was not appearing on the UI. The [TelemetryClient example](https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/master/telemetry_examples/src/main/java/com/newrelic/telemetry/examples/TelemetryClientExample.java#L97) uses `com.newrelic.telemetry.spans.Span;` where as the [exporter example](https://github.com/newrelic/opentelemetry-exporter-java/blob/master/src/test/java/com/newrelic/telemetry/opentelemetry/examples/BasicExample.java) uses `io.opentelemetry.trace.Span;`. I thought that perhaps using the New Relic version would prove to have better results, but I would prefer to use the exporter.

**Comment by jkwatson** [comment]
ah, ok. All the exporter does is convert OTel spans into NR spans and send them up, so if you're using OpenTelemetry, the exporter is definitely the way you want to go.

**Comment by litscher** [comment]
Okay. We finally found where the data was supposed to go as well.  Turns out I have been using the exporter right, we just were not looking in the right area. Thank you for your help and time on this

**Comment by jkwatson** [comment]
Glad I could help! Let us know if there is anything else we can help with.
