### ISSUE TITLE
Make the version-detection logic more robust

### ISSUE THREAD

**Issue by jkwatson** [newrelic/newrelic-telemetry-sdk-java#144]
From looking at user-agent metadata, it looks as though the SDK is being pulled into a fat jar, and we're reading the manifest of the fat jar, rather than the original SDK jar.  

We're ending up with user-agent strings that look like: "NewRelic-Java-TelemetrySDK/20.6.7029", which is definitely not a version that we've released.

This issue will also apply to all of our java-based exporters that are reading versions from the jar manifest.

**Comment by breedx-nr** [comment]
I don't think that the SDK is actually doing any manifest reading, and that this problem exists in whatever is calling `instrumentationProvider()` on the `MetricBatch` builder.  Right?  Can we close this here and address this in the libs that call this?

**Comment by jkwatson** [comment]
> I don't think that the SDK is actually doing any manifest reading, and that this problem exists in whatever is calling `instrumentationProvider()` on the `MetricBatch` builder. Right? Can we close this here and address this in the libs that call this?

https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/2f7410fc9a42c00fb8c15d2ca6e1c66bc0543d1e/telemetry_core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java#L44
