### ISSUE TITLE
Revisit the retry-with-splitting logic

### ISSUE THREAD

**Issue by kittylyst** [newrelic/newrelic-telemetry-sdk-java#150]
Post 0.5.0 we should revisit how the 413 response code (retry with split) is handled. It should probably be punted up to TelemetryClient

**Comment by breedx-nr** [comment]
This issue has been open for a while, and we are definitely post 0.5.0, so I'm wondering if this has already been addressed?  The TelemetryClient definitely tries to catch/split/retry the `RetryWithSplitException`
https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/12d667e38200269e99b694d2416bb68a43c79a8e/telemetry/src/main/java/com/newrelic/telemetry/TelemetryClient.java#L182
which is thrown in response to a 413 https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/12d667e38200269e99b694d2416bb68a43c79a8e/telemetry_core/src/main/java/com/newrelic/telemetry/transport/BatchDataSender.java#L140

Going to proactively close this, but @kittylyst please if you were thinking of something else please reopen and clarify.  Thanks!

**Comment by jkwatson** [comment]
Events still have their own implementation of splitting. this needs to be addressed.

**Comment by breedx-nr** [comment]
Ok, so this is specifically related to Events.  Thanks for the clarification.
