### ISSUE TITLE
Latest update has not been released

### ISSUE THREAD

**Issue by EstellaW94** [newrelic/newrelic-telemetry-sdk-java#162]
Hi, 
I noticed that there are couple of changes involving TelemetryClient and TelemetryClientExample have been made 14 days ago but without any release. I could not use the example yet because the create method in TelemetryClient could not be resolved.

Would you pls release the latest version ? Thanks!

**Comment by jkwatson** [comment]
Hi @EstellaW94 . Are you able to try out the `0.6.0-SNAPSHOT` build and see if it's working for you? We've been slowly working through some fallout from the changes in 0.5.x but we haven't been sure that 0.6.0 was ready for release yet.

**Comment by EstellaW94** [comment]
Thanks, it works! Hopefully we could see 0.6.0 in the near future!

**Comment by anup-streamotion** [comment]
Hi, I'm unable to build the 0.6.0-SNAPSHOT. Any ETA for 0.6.0 ?

**Comment by jkwatson** [comment]
I'd guess within the next week.

**Comment by jkwatson** [comment]
Hi @anup-streamotion and @EstellaW94 . We released 0.6.0 yesterday and it's available on maven central.

**Comment by XingzhiWang** [comment]
> Hi @anup-streamotion and @EstellaW94 . We released 0.6.0 yesterday and it's available on maven central.

Hi @jkwatson I already upgraded to 0.6.0. Thanks for letting me know!

**Comment by anup-streamotion** [comment]
Hey Thanks @jkwatson, I tested with 0.6.0 locally. Works good.
