### ISSUE TITLE
How to do an increment metric?

### ISSUE THREAD

**Issue by EstellaW94** [newrelic/newrelic-telemetry-sdk-java#164]
Hi, 
i am not sure whether this is the best place to ask the question. But i am unclear about doing an increment metric using telemetry sdk since there are only Count, Gauge and Summary. I would really appreciate for any suggestion or an example. 

Best,
Thanks!

**Comment by jkwatson** [comment]
Hi @EstellaW94 . Currently, the Telemetry SDK is a wrapper for the New Relic ingest APIs. This library doesn't contain higher-level abstractions like you are looking for. 

This would be an enhancement to the current SDK. Thank you for the suggestion!

In the meantime, if you need higher-level metrics library, we have exporters for Micrometer, Dropwizard metrics and OpenTelemetry metrics, all of which do provide these higher level constructs such as mutable counters, etc.

**Comment by breedx-nr** [comment]
Question was responded to and acknowledged by requestor.
