### ISSUE TITLE
Provide a helper method for adding error.message

### ISSUE THREAD

**Issue by prodjito** [newrelic/newrelic-telemetry-sdk-java#165]
Currently, SpanBuilder.withError() marks that a span is erroneous but does not take an error message as argument. The error message has to be separately added as an Attribute.

**Comment by prodjito** [comment]
@breedx-nr The Trace API requires that error attributes be prefixed with "error.", e.g. "error.class", "error.message" etc. In my opinion, the Telemetry SDK should provide a higher level abstraction so the user would not have to be aware of that Trace API requirement. As you suggested, it should allow the error message (and probably error class as well) to be passed as arguments to withError, which will then handle adding "error.class" and "error.message" attributes behind the scenes. In my opinion, the SDK shouldn't take away the user's ability to add error attributes directly so if they want to, they should still be able to add "error.class" and "error.message" attributes directly. Actually, I opened this issue on behalf of @jkwatson so he may have other ideas. Can you please reach out to him? Thanks!

**Comment by jkwatson** [comment]
As long as we document the behavior, I'm fine with either over-writing or ignoring as the behavior if `withError` is called twice with a different message (or lack of message).
