### ISSUE TITLE
Expose an API for retry/error detection

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-telemetry-sdk-java#166]
Users may wish to receive a signal when errors or retries happen, in order to provide backpressure to their upstream data source.  That is, when telemetry ingest problems happen, user code may wish to be signaled about this in order to relax upstream data flow.

One way to do this would be to allow the user to register a callback or set of callbacks (one per data type?) that are invoked with error condition details.

Recommend building one callback API for starters and to establish a pattern.

**Comment by kford-newrelic** [comment]
@breedx-nr this is a great feature suggestion - unfortunately, we're not able to prioritize this for the agent roadmap. We'll have to close with no further action.
