### ISSUE TITLE
Avoid infinite loop when getting 429 from NewRelic

### ISSUE THREAD

**Issue by vsanna** [newrelic/newrelic-telemetry-sdk-java#167]
Hi there,

I encountered one problem related with TelemetryClient, so please let me open an issue here.

I'm using micrometer-registry-new-relic(0.5.0), telemetry-core(0.4.0), telemetry(0.4.0).

## Background
When TelemetryClient is getting some kind of error from NewRelic(e.g. 429), it retries sending metrics without considering something like retryCount.
and this process is being executed on UserThread(TelmetryClient's executor), so this prevent JVM from shutting down while getting 429.

IMO, it's better for user to be able to control all of user-threads or I'd like to avoid using user-threads in libraries.

So I'd like you to consider 
- having its executor use ThreadFactory which makes its threads as daemon threads
- OR providing a constructor which we can inject our own executors from outside

## Suggestion
I hope option 2, so let me suggest option2 example..

In this line,
https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/8d81d9c6a076b39b71827aa857b029156f274e1a/telemetry/src/main/java/com/newrelic/telemetry/TelemetryClient.java#L41

```java
private final ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor(r -> {
	Thread thread = new Thread(r);
	thread.setDaemon(true);
	return thread;
});
```

If you don't mind, I will open a PR for this..

## Note
I've opened another Issue in newrelic/micrometer-registry-new-relic, but the issue is covering another problem

**Comment by jkwatson** [comment]
@vsanna yes, the threads definitely should be set to daemon in that executor. A PR would be welcome!

**Comment by jkwatson** [comment]
BTW, it looks like our max retry count is set to 10 here:  https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/master/telemetry/src/main/java/com/newrelic/telemetry/Backoff.java#L22

If that's not working, then that's definitely a bug which should be fixed ASAP.

**Comment by vsanna** [comment]
@jkwatson thank you for your comments.
As I see the code, I think code works like this.

1. (when 429) RetryWithRequestedWaitException is thrown and caught in sendWithErrorHandling
- retry
- scheduleBatchSend
- sendWithErrorHandling -> start again with 1

**Comment by jkwatson** [comment]
@vsanna yeah, this is definitely a bug in our 429 (RetryWithRequestedWaitException) handling in the TelemetryClient. Thanks for the report!

**Comment by breedx-nr** [comment]
I think https://github.com/paypay/newrelic-telemetry-sdk-java/pull/1 is intending to merge into this repo, so I put a note over there.

**Comment by vsanna** [comment]
@breedx-nr thank you for your comment, after getting approval internally, I will create new PR from our master branch to your master branch 🙇 
sorry for confusing 🙇

**Comment by vsanna** [comment]
@breedx-nr and this is another PR candidate.
https://github.com/paypay/newrelic-telemetry-sdk-java/pull/2/files

I think that this PR is better, but this requires extra change, so I'd appreciate if I could discuss with you about this

**Comment by breedx-nr** [comment]
Thank you @vsanna .  I have left notes on those two PRs and look forward to you being able to submit #1 against upstream.  🙏 🙇‍♂️
