### ISSUE TITLE
Create logging example in telemetry_examples/

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-telemetry-sdk-java#171]
A code example of how to use the logging support will be helpful to users.

**Comment by tbradellis** [comment]
I think this is already done...unless something different than below is needed.:
https://github.com/newrelic/newrelic-telemetry-sdk-java/blob/671ec9d81e4ad2908acfa5e610cc6a38f02c4ff8/telemetry_examples/src/main/java/com/newrelic/telemetry/examples/LogExample.java#L31

**Comment by XiXiaPdx** [comment]
@breedx-nr  Please see Brad's comment for current example. What were you thinking in terms of an example?

**Comment by XiXiaPdx** [comment]
This has been done
