### ISSUE TITLE
Have the TelemetryClient be less noisy after being shut down

### ISSUE THREAD

**Issue by jkwatson** [newrelic/newrelic-telemetry-sdk-java#176]
Right now, if you shut down the TelemetryClient, and some other background task is trying to send data with it, you will get a big `RejectedExecutionException`. I think that the client should check to see if it has been shut down and just log a message (INFO?) that it is not going to send the data.

**Comment by breedx-nr** [comment]
There's always going to be a race with this, though, right?  Like, it could get shut down at the same time that the check happened?  Maybe one `RejectedExecutionException` is better than the current behavior?

**Comment by jkwatson** [comment]
I was just thinking you could ask the Executor if it was up & running before doing the submit. But, yes, there will still be a small race condition that I think we can definitely live with.

**Comment by tbradellis** [comment]
pr #193

**Comment by jkwatson** [comment]
I don't think this solved the problem, because we'll still get the noisy stack trace from the logger.

**Comment by tbradellis** [comment]
Do we want to just not show the stack trace and log that there was an issue? And/or, do a check to see if the executor isTerminated in `scheduleBatchSend` just before attempting to schedule?
