### ISSUE TITLE
Add utility to help buffer and send when timeout or size limit is hit.

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-telemetry-sdk-java#187]
The goal here is to provide an easy way to build "Send after N seconds, or M data points, whichever comes first" (where N and M are configurable values).  This is already pretty easily built in the calling application code, but we anticipate this being useful for may SDK users and so should provide some helpful implementation for reuse.

This should probably leverage the `MetricBuffer` and `EventBuffer` classes since those exist, but what do we do about Spans and Logs?  Not sure, but this new thing probably sites above them.

**Comment by Jagoexchange** [comment]
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v3
- name: set up JDK 11
  uses: actions/setup-java@v3
  with:
    java-version: '11'
    distribution: 'temurin'
    cache: gradle

- name: Grant execute permission for gradlew
  run: chmod +x gradlew
- name: Build with Gradle
  run: ./gradlew build

**Comment by Jagoexchange** [comment]
[newrelic-telemetry-sdk-java-9bece66d1c0ff0db5c3f15aa44255a87da352ad0.zip](https://github.com/newrelic/newrelic-telemetry-sdk-java/files/8550724/newrelic-telemetry-sdk-java-9bece66d1c0ff0db5c3f15aa44255a87da352ad0.zip)

**Comment by kford-newrelic** [comment]
Initial prototyping work was done but will not prioritize this for further development on the agent roadmap.
