### ISSUE TITLE
Make it easy to select the EU region endpoints

### ISSUE THREAD

**Issue by jkwatson** [newrelic/newrelic-telemetry-sdk-java#188]
Right now, if you are a user in the EU, you have to manually configure the specific endpoints for EU ingest. We should make it easier to specify this. 

Possible implementation: Perhaps something akin to what the AWS SDKs provide where you can select a region, rather than having to always specify exact ingest endpoints.

**Comment by yamnihcg** [comment]
This has been resolved by adding a new method to the SenderConfigurationBuilder API (#276)
