### ISSUE TITLE
Don't retry on HTTP 429 forever

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-telemetry-sdk-java#189]
This is a follow-up from #167 .

The fix for #167 made threads daemon, but the root problem still remains:  429 errors returned from the endpoints cause the TelemetryClient to retry forever.  

There should be an upper limit to the number of consecutive retries.  I'm not sure what makes a sane default, because it might be dependent on the wait-after intervals commonly returned on 429.

**Comment by breedx-nr** [comment]
Because the 429 may be accompanied by a backoff time, we think that trying forever is probably the right approach.  The previous change to daemon threads should also allow the JVM to be shut down cleanly, even when the 429 loop is in progress.

Feel free to reopen if you would like to revisit this.

**Comment by breedx-nr** [comment]
We should come back to this, because we will continue to buffer new telemetry during periods of 429.  At some point we should probably start dropping data.

**Comment by XiXiaPdx** [comment]
429 are accompanied with a backoff time and there is also a limiting scheduler added in #251 . This issue is closed and please reopen if there is a need.
