### ISSUE TITLE
Trigger release based on github release

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-telemetry-sdk-java#211]
I think that we should favor the release process that we are setting up in other repos that triggers a release from a github release instead of detecting the version number.  That is, we currently see if the `-SNAPSHOT` suffix is present in order to do a release or not on merge to `main` branch.

Instead, we should configure our github action to be triggered from `release` event and append `-SNAPSHOT` to the version if we're not doing a release.

**Comment by XiXiaPdx** [comment]
This change was made and the current release process is triggered from github release.
