### ISSUE TITLE
Expose size of MetricBuffer

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-telemetry-sdk-java#213]
Users of the `MetricBuffer` class may wish to create+send a batch from the MetricBuffer once it has reached a certain size.  The MetricBuffer does not currently provide any way for users to determine the current buffer size, and thus it requires the user to track the size independently, which can add complexity and may be error prone.

Recommend adding a `size()` method to the MetricBuffer class to expose the size of the underlying queue.

**Comment by Yogendra0Sharma** [comment]
@breedx-nr Can I work on this issue? Please assign it to me.
