### ISSUE TITLE
Clean up javadocs warnings

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-telemetry-sdk-java#231]
There are a large number of javadoc warnings now when performing the build.  We should fix these to eliminate the warnings.

**Comment by uaihebert** [comment]
hello, could you assign it to me? I will look at it later.

**Comment by breedx-nr** [comment]
@uaihebert Sure thing, thank you!

**Comment by uaihebert** [comment]
Thank you.

One question, the integration tests fails like this: java.lang.IllegalStateException: Can not connect to Ryuk

Should I skip it? or is there a specific docker image to run?

**Comment by uaihebert** [comment]
Or should I do the build without the integration tests?

**Comment by uaihebert** [comment]
Hello, I was able to understand now what you mean. 
I will work on that soon.

Thank you

**Comment by uaihebert** [comment]
I think it will be better if we split it into smaller PRs.

There are a lot of updates required.

**Comment by breedx-nr** [comment]
@uaihebert Thanks again!  I think this is done so I'm going to close out now.
