### ISSUE TITLE
Consider dropping old data when telemetry size limit is reached.

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-telemetry-sdk-java#252]
This is a follow-up to #251.

The `LimitingScheduler` approach works by preventing newer batches of telemetry from being scheduled when a limit is reached.  Some users want the older data to be dropped so that the newer telemetry can be maintained.  This is not the approach that was chosen, but let's discuss here.

There is probably a tradeoff (pros/cons) to both approaches.  By maintaining older data, you possibly get insight into what was happening around the time that the problem started.  By maintaining newer data, you get improved continuity once the problem is resolved.

What else?  Do we want to change the implementation?

**Comment by kford-newrelic** [comment]
Not chosen for the agent roadmap.
