### ISSUE TITLE
Follow up on license/api key conversation

### ISSUE THREAD

**Issue by gfuller1** [newrelic/newrelic-telemetry-sdk-java#257]
Context: The SDK currently sends up data using an insights insert api key via the `Api-Key` header. Since there are several types of keys, what the customer should use can be confusing for customers. We hope to have the logic of how to handle different keys on the backend.

For this story we want to clarify which keys (license, api, insert) should work and which shouldn't work as headers in our Otel SDK requests and which headers we should send the keys in. This should be a discussion between our team and the architects to determine what the current expectations are.

Test if our OTel SDK is up to par with the expectations or if we need to make changes to it.

**Comment by rfelgent** [comment]
Hi @gfuller1,

can I somehow vote up for "license key" support ?

**Comment by XiXiaPdx** [comment]
Hi @rfelgent , the SDK accepts license keys now - https://github.com/newrelic/newrelic-telemetry-sdk-java/releases/tag/v0.12.0 😄   This is the revelant API in the PR to enable it.  

You'll provide your license key in the same parameter that use to be for the Insights key. The API above informs the SDK to send the key with the appropriate header to New Relic so it is evaluated as a license key. 

I'll try to update the docs very soon with a working example.

**Comment by XiXiaPdx** [comment]
This has been resolved as the sdk now accepts both Insights Insert Key and License Key  #271

**Comment by rfelgent** [comment]
thank you very much for the update! The feature "support license key" was a deal breaker for me...
