### ISSUE TITLE
Question/Suggestion -> How are the telemetry SDKs expected to be used in Serverless Function architectures?

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/newrelic-telemetry-sdk-java#283]
Customers are moving heavily into Serverless Function architectures like AWS Lambda.  How does NR expect customers to leverage the telemetry SDKs in these architectures?

And while Java might not be a popular language in general for AWS Lambda; the library breadth in enterprise environments means that it will be used in Lambda for some time.

**Comment by kford-newrelic** [comment]
@GaPeppy thanks for the question - you might want to take a look at our [Serverless monitoring docs page](https://docs.newrelic.com/docs/serverless-function-monitoring/overview/). Our Explorers Hub also has quite a bit of community discussion around [lambda monitoring](https://discuss.newrelic.com/tag/lambda).
