### ISSUE TITLE
Update okhttp3

### ISSUE THREAD

**Issue by Meridiano1984** [newrelic/newrelic-telemetry-sdk-java#309]
Hi, you are using `squareup.okhttp3:okhttp@4.10.0` this library depends on `com.squareup.okio:okio-jvm@3.0.0`. This version of okio-jvm has a vulnerability according to snyk: https://security.snyk.io/vuln/SNYK-JAVA-COMSQUAREUPOKIO-5820002.

Could you update `squareup.okhttp3` to get rid of this vulnerability?
I will be very grateful

**Comment by meiao** [comment]
Currently there is no newer version of okhttp.
If you are using Java 11+, you can use the `telemetry-http-java11` dependency instead of the okhttp one.

    implementation("com.newrelic.telemetry:telemetry-core:0.15.0")
    implementation("com.newrelic.telemetry:telemetry-http-java11:0.15.0")

**Comment by Meridiano1984** [comment]
ok, thank you for your response.

**Comment by meiao** [comment]
Fixed by #311 311
