### ISSUE TITLE
Restructure `metrics` to allow traces

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-telemetry-sdk-java#32]
At present, most of the functionality is within a module called `metrics`.  There is non-metric-specific code in this module (`HttpPoster` and `Attributes`, for example).  So, in order to better accommodate support for Traces, we should do some project restructuring and decide how to proceed (not yet sure which would be best).

## Idea 1: Rename `metrics` to `telemetry-core`

Pros:  Simple change, no code has to move.  Traces can sit next to Metrics in the same source module.

Cons:  Docs/deps change.  Published artifact names change.

## Idea 2:  Add modules `telemetry-core` and `traces`

Common/core code that can be shared between telemetry types would be moved into this new "core" module.  Establishes a pattern in which each telemetry type has its own module, and these modules depend on the core,

Pros: Simple.  Metrics artifact doesn't need to change.

Cons: Increased number of modules.  Increased dependency tree complexity.

## Idea 3: Put Traces into the metrics module

Pros: Least amount of work

Cons: Naming will be wrong.  Starts a pattern which will be harder to break when other telemetry types come into play.

**Comment by jkwatson** [comment]
this is very, very done.
