### ISSUE TITLE
Update HTTP Client [Telemetry SDK]

### ISSUE THREAD

**Issue by deleonenriqueta** [newrelic/newrelic-telemetry-sdk-java#325]
## Description
For Java 8, we currently provide an OkHttp client. OkHttp is slow to update when there are security alerts.
So providing an alternative that uses Apache HTTP is desired.

**Comment by kford-newrelic** [comment]
Related [convo](https://newrelic.slack.com/archives/C0NUYPJKA/p1721667234076149) on the topic
