### ISSUE TITLE
Change license headers

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-telemetry-sdk-java#43]
There is an internal doc that suggests we change the license header in all source from:
```
/*
 * ---------------------------------------------------------------------------------------------
 *  Copyright (c) 2019 New Relic Corporation. All rights reserved.
 *  Licensed under the Apache 2.0 License. See LICENSE in the project root directory for license information.
 * --------------------------------------------------------------------------------------------
 */
```

to this new format:

```
/*
 * Copyright 2019 New Relic Corporation. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
```

We should just do this all in one go.

**Comment by breedx-nr** [comment]
Might could use this:
https://source.datanerd.us/gist/jplumb/61891352288681a66a8402da1218bdad

**Comment by jkwatson** [comment]
or use the IDEA license plugin to do it all for us

**Comment by breedx-nr** [comment]
Or we could automate it and never have to think about it.  :)

**Comment by jkwatson** [comment]
definitely preferable, if you know a way. Is there a gradle plugin that will do it for us?

**Comment by breedx-nr** [comment]
Did it.
