### ISSUE TITLE
Provide a No-op implementation/option of the SDK

### ISSUE THREAD

**Issue by jkwatson** [newrelic/newrelic-telemetry-sdk-java#6]
Details needed on how this might be enabled.

The general idea is that there should be an easy way to keep the SDK in place, but simply disable any actual sending of data with a single (configuration?) change.

Details are here:  https://source.datanerd.us/agents/telemetry-sdk-specs/blob/master/configuration-and-logging.md#no-op-behavior

**Comment by breedx-nr** [comment]
We think we don't want to do this until there is a specific need/ask.
