### ISSUE TITLE
Update documentation to point at public API docs

### ISSUE THREAD

**Issue by jkwatson** [newrelic/newrelic-telemetry-sdk-java#7]
When they are available, we should link to them.

**Comment by jeffalder** [comment]
Which docs, @jkwatson ? This: https://docs.newrelic.com/docs/data-ingest-apis/get-data-new-relic/metric-api/report-metrics-metric-api ? Or Javadocs for the API for this module?

**Comment by jkwatson** [comment]
yes, those ones you referenced. the public ingest API documentation.  (also, the ones for the trace API)
